/*
 * Bsp_ST480MC.c
 *
 *  Created on: 2026年9月27日
 *      Author: yufan
 */

#include <Inc/Bsp_ST480MC.h>

/*
 * I2C1 handle generated by CubeMX
 */
extern I2C_HandleTypeDef hi2c1;


/* =========================================================
 * Private Variables
 * ========================================================= */

static volatile ST480MC_State_t s_st480mcState = ST480MC_STATE_IDLE;

static volatile uint8_t s_st480mcDone = 0U;
static volatile uint8_t s_st480mcError = 0U;

static volatile uint32_t s_st480mcErrorCode = 0U;

static uint8_t *s_st480mcRxBuffer = NULL;
static uint16_t s_st480mcRxSize = 0U;

static uint8_t s_st480mcLastStatus = 0U;


/* =========================================================
 * Private Function
 * ========================================================= */

static void ST480MC_ResetTransferState(void)
{
    s_st480mcDone = 0U;
    s_st480mcError = 0U;
    s_st480mcErrorCode = 0U;

    s_st480mcRxBuffer = NULL;
    s_st480mcRxSize = 0U;

    s_st480mcState = ST480MC_STATE_IDLE;
}


/* =========================================================
 * Initialize
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_Init(void)
{
    /*
     * I2C1 is initialized by CubeMX:
     *
     * PB8 -> SCL
     * PB9 -> SDA
     *
     * ST480MC:
     * A0 = GND
     * Address = 0x0C
     */

    ST480MC_ResetTransferState();

    return ST480MC_OK;
}


/* =========================================================
 * Is Busy
 * ========================================================= */

uint8_t Bsp_ST480MC_IsBusy(void)
{
    if ((s_st480mcState == ST480MC_STATE_TX) || (s_st480mcState == ST480MC_STATE_RX))
    {
        return 1U;
    }

    return 0U;
}


/* =========================================================
 * Get Last Status
 * ========================================================= */

uint8_t Bsp_ST480MC_GetLastStatus(void)
{
    return s_st480mcLastStatus;
}


/* =========================================================
 * TX + Repeated START + RX
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_TransmitReceive(
    uint8_t *pTxData,
    uint16_t txSize,
    uint8_t *pRxData,
    uint16_t rxSize)
{
    HAL_StatusTypeDef halStatus;
    uint32_t startTick;


    /* Parameter check */

    if ((pTxData == NULL) ||
        (txSize == 0U) ||
        (pRxData == NULL) ||
        (rxSize == 0U))
    {
        return ST480MC_ERROR;
    }


    /* Check driver busy */

    if (Bsp_ST480MC_IsBusy())
    {
        return ST480MC_BUSY;
    }


    /* Check HAL I2C state */

    if (HAL_I2C_GetState(&hi2c1) != HAL_I2C_STATE_READY)
    {
        return ST480MC_BUSY;
    }


    /* Reset state */

    ST480MC_ResetTransferState();

    s_st480mcRxBuffer = pRxData;
    s_st480mcRxSize = rxSize;

    s_st480mcState = ST480MC_STATE_TX;


    /*
     * First frame:
     *
     * START
     * Slave + W
     * TX DATA
     *
     * DO NOT generate STOP
     */
    halStatus = HAL_I2C_Master_Seq_Transmit_IT(
                    &hi2c1,
                    ST480MC_I2C_ADDR,
                    pTxData,
                    txSize,
                    I2C_FIRST_FRAME);


    if (halStatus != HAL_OK)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    /*
     * Wait for:
     *
     * TX complete
     * Repeated START
     * RX complete
     *
     * Callback functions are executed in IRQ.
     */
    startTick = HAL_GetTick();

    while (s_st480mcDone == 0U)
    {
        if (s_st480mcError != 0U)
        {
            ST480MC_ResetTransferState();
            return ST480MC_ERROR;
        }


        if ((HAL_GetTick() - startTick) >=
            ST480MC_I2C_TIMEOUT)
        {
            ST480MC_ResetTransferState();
            return ST480MC_TIMEOUT;
        }
    }


    /*
     * Check result
     */
    if (s_st480mcError != 0U)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    ST480MC_ResetTransferState();

    return ST480MC_OK;
}


/* =========================================================
 * TX Complete Callback
 * ========================================================= */

void HAL_I2C_MasterTxCpltCallback(
    I2C_HandleTypeDef *hi2c)
{
    HAL_StatusTypeDef halStatus;


    if (hi2c != &hi2c1)
    {
        return;
    }


    /*
     * TX -> RX transaction
     */
    if (s_st480mcState == ST480MC_STATE_TX)
    {
        /*
         * 如果没有 RX buffer，
         * 说明这是单纯 TX。
         */
        if ((s_st480mcRxBuffer == NULL) ||
            (s_st480mcRxSize == 0U))
        {
            s_st480mcState =
                ST480MC_STATE_DONE;

            s_st480mcDone = 1U;

            return;
        }


        /*
         * TX 完成后进入 RX
         *
         * REPEATED START
         * Slave + R
         * RX
         * STOP
         */
        s_st480mcState =
            ST480MC_STATE_RX;


        halStatus =
            HAL_I2C_Master_Seq_Receive_IT(
                &hi2c1,
                ST480MC_I2C_ADDR,
                s_st480mcRxBuffer,
                s_st480mcRxSize,
                I2C_LAST_FRAME);


        if (halStatus != HAL_OK)
        {
            s_st480mcError = 1U;

            s_st480mcErrorCode =
                HAL_I2C_GetError(&hi2c1);

            s_st480mcState =
                ST480MC_STATE_ERROR;

            s_st480mcDone = 1U;
        }
    }
}


/* =========================================================
 * RX Complete Callback
 * ========================================================= */

void HAL_I2C_MasterRxCpltCallback(
    I2C_HandleTypeDef *hi2c)
{
    if (hi2c != &hi2c1)
    {
        return;
    }


    if (s_st480mcState != ST480MC_STATE_RX)
    {
        return;
    }


    /*
     * RX finished.
     *
     * I2C_LAST_FRAME will generate STOP.
     */
    s_st480mcState =
        ST480MC_STATE_DONE;

    s_st480mcDone = 1U;
}


/* =========================================================
 * Error Callback
 * ========================================================= */

void HAL_I2C_ErrorCallback(
    I2C_HandleTypeDef *hi2c)
{
    if (hi2c != &hi2c1)
    {
        return;
    }


    /*
     * Only handle ST480MC transaction
     */
    if ((s_st480mcState == ST480MC_STATE_TX) ||
        (s_st480mcState == ST480MC_STATE_RX))
    {
        s_st480mcError = 1U;

        s_st480mcErrorCode =
            HAL_I2C_GetError(&hi2c1);

        s_st480mcState =
            ST480MC_STATE_ERROR;

        s_st480mcDone = 1U;
    }
}


/* =========================================================
 * Send Command
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_SendCommand(
    uint8_t cmd)
{
    HAL_StatusTypeDef halStatus;
    uint32_t startTick;


    if (Bsp_ST480MC_IsBusy())
    {
        return ST480MC_BUSY;
    }


    if (HAL_I2C_GetState(&hi2c1) != HAL_I2C_STATE_READY)
    {
        return ST480MC_BUSY;
    }


    ST480MC_ResetTransferState();

    s_st480mcState =
        ST480MC_STATE_TX;


    /*
     * Single frame:
     *
     * START
     * Slave + W
     * CMD
     * STOP
     */
    halStatus =
        HAL_I2C_Master_Seq_Transmit_IT(
            &hi2c1,
            ST480MC_I2C_ADDR,
            &cmd,
            1U,
            I2C_FIRST_AND_LAST_FRAME);


    if (halStatus != HAL_OK)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    startTick = HAL_GetTick();


    while (s_st480mcDone == 0U)
    {
        if (s_st480mcError != 0U)
        {
            ST480MC_ResetTransferState();
            return ST480MC_ERROR;
        }


        if ((HAL_GetTick() - startTick) >=
            ST480MC_I2C_TIMEOUT)
        {
            ST480MC_ResetTransferState();
            return ST480MC_TIMEOUT;
        }
    }


    if (s_st480mcError != 0U)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    ST480MC_ResetTransferState();

    return ST480MC_OK;
}


/* =========================================================
 * Command Write
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_CommandWrite(
    uint8_t *pData,
    uint16_t size)
{
    HAL_StatusTypeDef halStatus;
    uint32_t startTick;


    if ((pData == NULL) ||
        (size == 0U))
    {
        return ST480MC_ERROR;
    }


    if (Bsp_ST480MC_IsBusy())
    {
        return ST480MC_BUSY;
    }


    if (HAL_I2C_GetState(&hi2c1) != HAL_I2C_STATE_READY)
    {
        return ST480MC_BUSY;
    }


    ST480MC_ResetTransferState();

    s_st480mcState =
        ST480MC_STATE_TX;


    halStatus =
        HAL_I2C_Master_Seq_Transmit_IT(
            &hi2c1,
            ST480MC_I2C_ADDR,
            pData,
            size,
            I2C_FIRST_AND_LAST_FRAME);


    if (halStatus != HAL_OK)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    startTick = HAL_GetTick();


    while (s_st480mcDone == 0U)
    {
        if (s_st480mcError != 0U)
        {
            ST480MC_ResetTransferState();
            return ST480MC_ERROR;
        }


        if ((HAL_GetTick() - startTick) >=
            ST480MC_I2C_TIMEOUT)
        {
            ST480MC_ResetTransferState();
            return ST480MC_TIMEOUT;
        }
    }


    if (s_st480mcError != 0U)
    {
        ST480MC_ResetTransferState();
        return ST480MC_ERROR;
    }


    ST480MC_ResetTransferState();

    return ST480MC_OK;
}


/* =========================================================
 * Command Read
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_CommandRead(
    uint8_t *pData,
    uint16_t txSize,
    uint8_t *pRxData,
    uint16_t rxSize)
{
    return Bsp_ST480MC_TransmitReceive(
        pData,
        txSize,
        pRxData,
        rxSize);
}


/* =========================================================
 * Read Register
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_ReadReg(
    uint8_t reg,
    uint16_t *data)
{
    uint8_t txData[2];
    uint8_t rxData[3];

    ST480MC_Status_t status;


    if (data == NULL)
    {
        return ST480MC_ERROR;
    }


    /*
     * TX:
     *
     * 0x50
     * Register Address
     */
    txData[0] =
        ST480MC_CMD_RR;

    txData[1] =
        reg;


    /*
     * RX:
     *
     * Status
     * Register High
     * Register Low
     */
    status =
        Bsp_ST480MC_TransmitReceive(
            txData,
            2U,
            rxData,
            3U);


    if (status != ST480MC_OK)
    {
        return status;
    }


    /*
     * Save status byte
     */
    s_st480mcLastStatus =
        rxData[0];


    /*
     * Check sensor ERROR bit
     */
    if ((rxData[0] &
         ST480MC_STATUS_ERROR) != 0U)
    {
        return ST480MC_ERROR;
    }


    /*
     * Big endian
     */
    *data =
        ((uint16_t)rxData[1] << 8) |
        ((uint16_t)rxData[2]);


    return ST480MC_OK;
}


/* =========================================================
 * Write Register
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_WriteReg(
    uint8_t reg,
    uint16_t data)
{
    uint8_t txData[4];


    /*
     * ST480MC WR protocol:
     *
     * 0x60
     * High
     * Low
     * Register Address
     */

    txData[0] =
        ST480MC_CMD_WR;

    txData[1] =
        (uint8_t)(data >> 8);

    txData[2] =
        (uint8_t)(data & 0xFFU);

    txData[3] =
        reg;


    return Bsp_ST480MC_CommandWrite(
        txData,
        4U);
}


/* =========================================================
 * Start Single Measurement
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_StartMeasurement(void)
{
    return Bsp_ST480MC_SendCommand(
        ST480MC_CMD_SM_XYZ);
}


/* =========================================================
 * Read XYZ Measurement
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_ReadMeasurement(
    ST480MC_RawData_t *data)
{
    uint8_t cmd;
    uint8_t rxData[7];

    ST480MC_Status_t status;


    if (data == NULL)
    {
        return ST480MC_ERROR;
    }


    /*
     * Read Measurement:
     *
     * 0x4E
     *
     * RX:
     *
     * Status
     * X High
     * X Low
     * Y High
     * Y Low
     * Z High
     * Z Low
     */
    cmd =
        ST480MC_CMD_RM_XYZ;


    status =
        Bsp_ST480MC_TransmitReceive(
            &cmd,
            1U,
            rxData,
            7U);


    if (status != ST480MC_OK)
    {
        return status;
    }


    /*
     * Save status
     */
    s_st480mcLastStatus =
        rxData[0];


    /*
     * Sensor reported error
     */
    if ((rxData[0] &
         ST480MC_STATUS_ERROR) != 0U)
    {
        return ST480MC_ERROR;
    }


    /*
     * Convert big-endian data
     */
    data->X =
        (int16_t)(
            ((uint16_t)rxData[1] << 8) |
            ((uint16_t)rxData[2])
        );


    data->Y =
        (int16_t)(
            ((uint16_t)rxData[3] << 8) |
            ((uint16_t)rxData[4])
        );


    data->Z =
        (int16_t)(
            ((uint16_t)rxData[5] << 8) |
            ((uint16_t)rxData[6])
        );


    return ST480MC_OK;
}


/* =========================================================
 * Measure XYZ
 * ========================================================= */

ST480MC_Status_t Bsp_ST480MC_MeasureXYZ(
    ST480MC_RawData_t *data)
{
    ST480MC_Status_t status;


    if (data == NULL)
    {
        return ST480MC_ERROR;
    }


    /*
     * Step 1:
     * Start single measurement
     */
    status =
        Bsp_ST480MC_StartMeasurement();


    if (status != ST480MC_OK)
    {
        return status;
    }


    /*
     * Step 2:
     * Read measurement
     */
    status =
        Bsp_ST480MC_ReadMeasurement(data);


    return status;
}
